### ISSUE TITLE
Flexible callback forms

### ISSUE THREAD

**Issue by alphapapa** [Alexander-Miller/pfuture#3]
As mentioned here: https://www.reddit.com/r/emacs/comments/8x57ck/deadgrep_fast_friendly_searching_with_ripgrep_and/e29h58l/?context=3

What if we did it like this?

```el
(defmacro argh (fn)
  `(let ((foo 'foo))
     ,(pcase fn
        (`(function ,fn) `(,fn foo))
        (`(,_ . ,_) fn)
        (fn `(funcall ,fn foo)))))

(argh #'identity)  ;; => foo

(let ((the-fn #'identity))
  (argh the-fn))  ;; => foo

(let ((the-fn (lambda (it)
                (identity it))))
  (argh the-fn))  ;; => foo

(argh (identity foo))  ;; => foo
```
That would allow for all 4 forms to be used as a callback: a function symbol, a lambda stored in a symbol's variable value, a function's symbol stored in a variable's value, and a sexp.

**Comment by Alexander-Miller** [comment]
It's an improvement over the current approach, but this cannot distinguish between symbols storing functions in their function or their value slot. `(argh ignore)` causes an error, though I suppose this as acceptable since if you pass the name of an actual function you should sharp-quote it anyway.

The changes are up now, including the collection the output in a buffer.

**Comment by alphapapa** [comment]
> It's an improvement over the current approach, but this cannot distinguish between symbols storing functions in their function or their value slot.

I don't think anything can do that except the user calling the macro, right?

> (argh ignore) causes an error, though I suppose this as acceptable since if you pass the name of an actual function you should sharp-quote it anyway.

Yes, unless the user's let-binding `ignore` to a lambda, right?

**Comment by Alexander-Miller** [comment]
> I don't think anything can do that except the user calling the macro, right?

I guess it's possible to check at expansion/load/compile time, but I'm 
not sure how that'd work for local, lexical, let-bound stuff. The 
current approach is distinct and clear enough I think.


> Yes, unless the user's let-binding ignore to a lambda, right?

Yes.

**Comment by Alexander-Miller** [comment]
Anything you see missing in the current form?

**Comment by Alexander-Miller** [comment]
Net gschimpft isch lob gnug.
