### ISSUE TITLE
Decoding issue (maybe?) with a simple Python script

### ISSUE THREAD

**Issue by y-usuzumi** [Alexander-Miller/pfuture#6]
Alexander-Miller/treemacs#65

I played with pfuture a little bit and found it could not decode CJK characters correctly:

with this simple Python script:

```python
#!/usr/bin/python
import sys
print(sys.argv)
```

And call it with this:

```elisp
(setq f (pfuture-new "python" "/home/kj/x.py" "你好"))
(pfuture-await f :timeout 4 :just-this-one nil)
(pfuture-result f)
```
I got this result:
![image](https://user-images.githubusercontent.com/1560189/71577143-f3add580-2b2d-11ea-9cec-36742c655320.png)

**Comment by Alexander-Miller** [comment]
Should be fixed now.
