### ISSUE TITLE
Can we use temporary buffer for stdout?

### ISSUE THREAD

**Issue by puuuuh** [Alexander-Miller/pfuture#7]
Emacs spend 90% time in GC, bacause pfuture--append-stdout do too many allocations for large output

**Comment by Alexander-Miller** [comment]
Sure thing.

**Comment by Alexander-Miller** [comment]
Stdout will be collected in a buffer now. Stderr still uses the old approach, but I figure it should happen rarely enough that the status quo is less wasteful than always creating a second buffer.
